language: php

sudo: false

services:
    - redis-server

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.2
    - 7.3

matrix:
    fast_finish: true

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer test
